version: '3.8'
services:
  postgres:
    image: postgres:16.3
    container_name: postgres16
    environment:
      POSTGRES_USER: school
      POSTGRES_PASSWORD: school
      POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
